config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource  :sms, only: [:create, :show]

  resource  :session, only: [:new, :create, :destroy]
  root      "welcome#index"
end

app/models/twilio_integration.rb
class TwilioIntegration
  attr_reader :client, :account

  def initialize
    @client  = TwilioHelper::CLIENT
    @account = @client.account
  end

  def send(phone_number, message)
    @account.messages.create(
      from: TwilioHelper::PHONE,
      to:   phone_number,
      body: message
    )
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :name,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  helper_method :current_user, :logged_in?
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    # find if any user has that email
    user = User.find_by(email: params[:email])
    
    # if that user exists and it has a password that was sent
    if user && user.authenticate(params[:password])
      
      # save the user_id in the session hash
      session[:user_id] = user.id

      # and redirect to that user's home page
      redirect_to users_path
    else
      # the email/password is wrong!
      @message = "This email and password combination does not exist."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/sms_controller.rb
class SmsController < ApplicationController
  before_action :authenticate

  def create
    sms          = TwilioIntegration.new
    phone_number = "+1#{params[:phone_number]}"
    message      = params[:message]

    logger.info sms.send(phone_number, message)
    redirect_to "#{sms_path}?phone_number=#{phone_number}&message=#{URI.encode message}"
  end

  def show
    @phone_number = params[:phone_number]
    @message      = URI.decode params[:message]
  end

  private

    def authenticate
      unless logged_in?
        redirect_to new_session_path
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:new, :create, :index]
  before_action :authenticate, except: [:new, :create]
  before_action :authorize,    only:   [:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end

  def authenticate
    unless logged_in?
      redirect_to new_session_path
    end
  end

  def authorize
    unless current_user == @user
      redirect_to new_session_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to users_path if logged_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twilio_helper.rb
module TwilioHelper
  CLIENT = Twilio::REST::Client.new(
    ENV['TWILIO_ACCT_SID'], 
    ENV['TWILIO_AUTH_TOKEN']
  )

  PHONE = "+1#{ENV['TWILIO_PHONE_NO']}"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>McClane Minihack</title>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <h1><%= link_to "Welcome to the Rails <3s Twilio Template!", root_path %></h1>
  <%= yield %>

</body>
</html>

app/views/sms/show.html.erb
<p>You have sent the message <strong>'<%= @message %>'</strong> to the phone number
<strong><%= @phone_number %></strong>.</p>

<%= link_to 'Return to User List', users_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h4>Send a text message:</h4>

<%= form_tag sms_path do %>
  <%= submit_tag "Send" %>
  <%= label_tag :message, "Message:" %>
  <%= text_field_tag :message %>
  <%= label_tag :phone_number, "Phone Number: +1" %>
  <%= text_field_tag :phone_number %> (enter only numbers, no spaces or symbols)
<% end %>

<br>
<%= link_to 'Log Out', session_path, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back to User List', users_path %>

app/views/welcome/index.html.erb
<p>
  <%= link_to 'Sign Up', new_user_path %><br>
  <%= link_to 'Log In',  new_session_path %>
</p>